name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:


      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'


      - name: Build with gradle
        run: ./gradlew build --stacktrace

      - name: Run Testts
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

  lint-check:
    name: 🔍 Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint check
        run: ./gradlew lint

      - name: Generate lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint_report.html
          path: app/build/reports/lint-results-debug.html


#name: Android Build
#
#on: pull_request
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Set Up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Run Tests
#        run: ./gradlew test
#
#      - name: Build Project
#        run: ./gradlew assemble
#
#